import chalk from 'chalk';
import boxen from 'boxen';
import fs from 'fs';
import { LocalAnalysisResult } from './analyzer.js';
import { GeminiAnalysisResult } from './gemini.js';

/**
 * Colorizes a letter grade.
 */
function colorGrade(grade: string): string {
  const cleanGrade = grade.trim().toUpperCase();
  if (cleanGrade.startsWith('A')) return chalk.bold.greenBright(grade);
  if (cleanGrade.startsWith('B')) return chalk.bold.cyanBright(grade);
  if (cleanGrade.startsWith('C')) return chalk.bold.yellowBright(grade);
  if (cleanGrade.startsWith('D')) return chalk.bold.red(grade);
  return chalk.bold.redBright(grade);
}

/**
 * Colorizes score numbers.
 */
function colorScore(score: number): string {
  if (score >= 90) return chalk.greenBright(`${score}/100`);
  if (score >= 75) return chalk.cyanBright(`${score}/100`);
  if (score >= 50) return chalk.yellowBright(`${score}/100`);
  return chalk.redBright(`${score}/100`);
}

/**
 * Generates the text report based on selected format.
 */
export function formatReport(
  owner: string,
  repo: string,
  localData: LocalAnalysisResult,
  aiData: GeminiAnalysisResult,
  format: 'json' | 'markdown' | 'table'
): string {
  if (format === 'json') {
    return JSON.stringify({
      owner,
      repo,
      localAnalysis: {
        fileCount: localData.fileCount,
        totalLines: localData.totalLines,
        languages: localData.languages,
        hasReadme: localData.hasReadme,
        hasLicense: localData.hasLicense,
        hasApiDocs: localData.hasApiDocs,
        testFrameworks: localData.testFrameworks,
        npmDependenciesCount: localData.dependencies.length,
        pythonDependenciesCount: localData.pythonDependencies.length,
        rustDependenciesCount: localData.rustDependencies.length,
        goDependenciesCount: localData.goDependencies.length,
        dockerAlertsCount: localData.dockerAlerts.length,
        todoCount: localData.todoCount
      },
      aiAnalysis: aiData
    }, null, 2);
  }

  if (format === 'markdown') {
    const secIssuesMd = aiData.securityIssues.length > 0
      ? aiData.securityIssues.map(issue => `| **${issue.severity.toUpperCase()}** | \`${issue.file}\` | ${issue.description} |`).join('\n')
      : '| *None* | | No security issues detected. |';

    const strengthsMd = aiData.keyStrengths.map(s => `- ${s}`).join('\n');
    const weaknessesMd = aiData.keyWeaknesses.map(w => `- ${w}`).join('\n');
    const recsMd = aiData.recommendations.map(r => `- ${r}`).join('\n');

    return `# DevProbe Analysis Report: ${owner}/${repo}

## 📊 Summary Dashboard
- **Overall Grade:** **${aiData.overallGrade}**
- **Code Quality Score:** ${aiData.codeQualityScore}/100
- **Security Score:** ${aiData.securityScore}/100

| Metric | Status / Value |
| --- | --- |
| **Total Files** | ${localData.fileCount} |
| **Lines of Code** | ${localData.totalLines} |
| **Test Suite** | ${localData.testFrameworks.length > 0 ? `Detected (${localData.testFrameworks.join(', ')})` : 'Not configured'} |
| **Documentation** | README: ${localData.hasReadme ? 'Yes' : 'No'} \| License: ${localData.hasLicense ? 'Yes' : 'No'} \| API Docs: ${localData.hasApiDocs ? 'Yes' : 'No'} |
| **TODO/FIXME Comments** | ${localData.todoCount} |

---

## 🛡️ Security Audit
| Severity | File | Description |
| --- | --- | --- |
${secIssuesMd}

---

## 📋 Detailed Analysis

### ⭐ Key Strengths
${strengthsMd}

### ⚠️ Areas for Improvement
${weaknessesMd}

### 💡 Actionable Recommendations
${recsMd}

---
*Report generated by DevProbe on ${new Date().toLocaleDateString()}*
`;
  }

  // DEFAULT: table/terminal format
  const reportLines: string[] = [];
  reportLines.push(chalk.bold('📊 DevProbe Report'));
  reportLines.push(`├── Code Quality:     ${colorScore(aiData.codeQualityScore)} (${aiData.codeQualityRationale.substring(0, 55)}...)`);
  
  const secCount = aiData.securityIssues.length;
  const secText = secCount === 0 
    ? chalk.greenBright('Passed (no issues found)') 
    : chalk.yellowBright(`⚠️  ${secCount} issue${secCount > 1 ? 's' : ''} found`);
  reportLines.push(`├── Security:         ${secText}`);

  const deprecatedCount = localData.dependencies.filter(d => d.isDeprecated).length;
  const outdatedCount = localData.dependencies.filter(d => d.isOutdated).length;
  const totalDeps = localData.dependencies.length + localData.pythonDependencies.length + localData.rustDependencies.length + localData.goDependencies.length;
  
  let depText = '';
  if (deprecatedCount === 0 && outdatedCount === 0) {
    depText = chalk.greenBright(`Up to date & clean (${totalDeps} packages found)`);
  } else {
    const parts: string[] = [];
    if (outdatedCount > 0) parts.push(chalk.yellow(`${outdatedCount} outdated`));
    if (deprecatedCount > 0) parts.push(chalk.red(`${deprecatedCount} deprecated`));
    depText = parts.join(', ') + ` (checked npm dependencies)`;
  }
  reportLines.push(`├── Dependencies:     ${depText}`);

  const testText = localData.testFrameworks.length > 0 || localData.testDirsDetected
    ? chalk.greenBright(`Detected (${localData.testFrameworks.join(', ') || 'test directory'})`)
    : chalk.redBright('No tests detected');
  reportLines.push(`├── Test Coverage:    ${testText}`);

  const docParts: string[] = [];
  docParts.push(localData.hasReadme ? chalk.green('README') : chalk.red('No README'));
  docParts.push(localData.hasLicense ? chalk.green('LICENSE') : chalk.red('No LICENSE'));
  if (localData.hasApiDocs) docParts.push(chalk.green('API docs'));
  reportLines.push(`├── Documentation:    ${docParts.join(', ')}`);
  reportLines.push(`└── Overall Grade:    ${colorGrade(aiData.overallGrade)}`);

  let finalOutput = `\n${chalk.bold.cyan(`🔍 DevProbe Analysis for ${owner}/${repo}`)}\n\n` + reportLines.join('\n') + '\n\n';

  if (secCount > 0) {
    finalOutput += chalk.bold.red('⚠️  Detailed Security Issues:\n');
    aiData.securityIssues.forEach((issue, index) => {
      const severityStr = issue.severity === 'high' 
        ? chalk.bold.red('[HIGH]') 
        : issue.severity === 'medium' 
          ? chalk.bold.yellow('[MEDIUM]') 
          : chalk.bold.blue('[LOW]');
      finalOutput += `  ${index + 1}. ${severityStr} ${chalk.cyan(issue.file)}: ${issue.description}\n`;
    });
    finalOutput += '\n';
  }

  let boxContent = '';
  boxContent += chalk.bold.green('⭐ Key Strengths:\n');
  aiData.keyStrengths.forEach(str => { boxContent += ` • ${str}\n`; });
  boxContent += '\n' + chalk.bold.yellow('⚠️  Areas for Improvement:\n');
  aiData.keyWeaknesses.forEach(weak => { boxContent += ` • ${weak}\n`; });
  boxContent += '\n' + chalk.bold.cyan('💡 Actionable Recommendations:\n');
  aiData.recommendations.forEach(rec => { boxContent += ` • ${rec}\n`; });

  const styledBox = boxen(boxContent.trim(), {
    title: chalk.bold.blue('📋 Detailed AI Analysis'),
    titleAlignment: 'center',
    padding: 1,
    borderStyle: 'round',
    borderColor: 'cyan'
  });

  return finalOutput + styledBox + '\n';
}

/**
 * Outputs report to console or file based on options.
 */
export function outputReport(
  owner: string,
  repo: string,
  localData: LocalAnalysisResult,
  aiData: GeminiAnalysisResult,
  format: 'json' | 'markdown' | 'table',
  outputFile?: string
): void {
  const content = formatReport(owner, repo, localData, aiData, format);

  if (outputFile) {
    fs.writeFileSync(outputFile, content, 'utf8');
    console.log(chalk.green(`\n💾 Report successfully written to: ${chalk.bold(outputFile)}`));
  } else {
    console.log(content);
  }
}

/**
 * Draws a side-by-side terminal comparison between two repositories.
 */
export function printCompareReport(
  repo1: { owner: string; repo: string; local: LocalAnalysisResult; ai: GeminiAnalysisResult },
  repo2: { owner: string; repo: string; local: LocalAnalysisResult; ai: GeminiAnalysisResult }
): void {
  const colWidth = 28;
  const metricColWidth = 22;

  const repo1Label = `${repo1.owner}/${repo1.repo}`.substring(0, colWidth - 2);
  const repo2Label = `${repo2.owner}/${repo2.repo}`.substring(0, colWidth - 2);

  // Formatting helpers that ignore ANSI escape sequences for length calculation
  const stripAnsi = (str: string) => str.replace(/[\u001b\u009b][[()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-9A-ORZcf-nqry=><]/g, '');

  const padRight = (str: string, len: number) => {
    const visibleLen = stripAnsi(str).length;
    return str + ' '.repeat(Math.max(0, len - visibleLen));
  };

  const padCenter = (str: string, len: number) => {
    const visibleLen = stripAnsi(str).length;
    const diff = len - visibleLen;
    if (diff <= 0) return str;
    const left = Math.floor(diff / 2);
    const right = diff - left;
    return ' '.repeat(left) + str + ' '.repeat(right);
  };

  const drawRow = (metric: string, val1: string, val2: string) => {
    console.log(`│ ${padRight(metric, metricColWidth)} │ ${padCenter(val1, colWidth)} │ ${padCenter(val2, colWidth)} │`);
  };

  console.log('\n' + chalk.bold.magenta('🆚 DEVPROBE REPOSITORY COMPARISON') + '\n');

  console.log(`┌${'─'.repeat(metricColWidth + 2)}┬${'─'.repeat(colWidth + 2)}┬${'─'.repeat(colWidth + 2)}┐`);
  console.log(`│ ${padRight(chalk.bold('Comparison Metric'), metricColWidth)} │ ${padCenter(chalk.bold.cyan(repo1Label), colWidth)} │ ${padCenter(chalk.bold.yellow(repo2Label), colWidth)} │`);
  console.log(`├${'─'.repeat(metricColWidth + 2)}┼${'─'.repeat(colWidth + 2)}┼${'─'.repeat(colWidth + 2)}┤`);

  drawRow('Overall Grade', colorGrade(repo1.ai.overallGrade), colorGrade(repo2.ai.overallGrade));
  drawRow('Code Quality Score', colorScore(repo1.ai.codeQualityScore), colorScore(repo2.ai.codeQualityScore));
  drawRow('Security Score', colorScore(repo1.ai.securityScore), colorScore(repo2.ai.securityScore));
  
  const secIssues1 = repo1.ai.securityIssues.length;
  const secIssues2 = repo2.ai.securityIssues.length;
  drawRow(
    'Security Issues',
    secIssues1 === 0 ? chalk.green('0 issues') : chalk.red(`${secIssues1} found`),
    secIssues2 === 0 ? chalk.green('0 issues') : chalk.red(`${secIssues2} found`)
  );

  drawRow('Total Files Count', repo1.local.fileCount.toString(), repo2.local.fileCount.toString());
  drawRow('Lines of Code (est.)', repo1.local.totalLines.toString(), repo2.local.totalLines.toString());
  
  // Dependencies summary
  const npmCount1 = repo1.local.dependencies.length;
  const npmCount2 = repo2.local.dependencies.length;
  const pyCount1 = repo1.local.pythonDependencies.length;
  const pyCount2 = repo2.local.pythonDependencies.length;
  const rsCount1 = repo1.local.rustDependencies.length;
  const rsCount2 = repo2.local.rustDependencies.length;
  const goCount1 = repo1.local.goDependencies.length;
  const goCount2 = repo2.local.goDependencies.length;

  const depSum = (npm: number, py: number, rs: number, go: number) => {
    const list: string[] = [];
    if (npm > 0) list.push(`${npm} NPM`);
    if (py > 0) list.push(`${py} Python`);
    if (rs > 0) list.push(`${rs} Rust`);
    if (go > 0) list.push(`${go} Go`);
    return list.join(', ') || 'None';
  };

  drawRow('Dependencies Ecosystem', depSum(npmCount1, pyCount1, rsCount1, goCount1), depSum(npmCount2, pyCount2, rsCount2, goCount2));

  const testSum = (loc: LocalAnalysisResult) => {
    if (loc.testFrameworks.length > 0) return loc.testFrameworks.join(', ');
    if (loc.testDirsDetected) return 'Spec/Tests folder';
    return 'None detected';
  };
  drawRow('Testing Suite', testSum(repo1.local), testSum(repo2.local));

  const docSum = (loc: LocalAnalysisResult) => {
    const list: string[] = [];
    if (loc.hasReadme) list.push('README');
    if (loc.hasLicense) list.push('LICENSE');
    if (loc.hasApiDocs) list.push('API Docs');
    return list.join(', ') || 'None';
  };
  drawRow('Documentation Files', docSum(repo1.local), docSum(repo2.local));

  console.log(`└${'─'.repeat(metricColWidth + 2)}┴${'─'.repeat(colWidth + 2)}┴${'─'.repeat(colWidth + 2)}┘\n`);
}
